language: python
python:
  - "3.7"
cache:
  pip: true
install:
  - pip install pipenv
  - pip install coverage
  - pip install codecov
env:
  - TEST_DIR=hokuto_flask
  - TEST_DIR=hokuto_scraping
script: cd $TEST_DIR && pipenv install --dev && pipenv run coverage run -m pytest -v
after_success:
  - codecov
notifications:
    email:
        on_success: change
        on_failure: always
