"""Add all tables.

This migration script should work both with SQLite and PostgreSQL.

If you want Alembic (via Flask-Migrate) to detect datatype changes, instantiate
the Flask-Migrate extension with `Migrate(compare_type=True)`.

Revision ID: 5363bcfa9690
Revises: 
Create Date: 2018-09-05 21:55:03.937279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5363bcfa9690'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.String(length=32), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_categories_name'), 'categories', ['name'], unique=True)
    op.create_table('characters',
    sa.Column('id', sa.String(length=32), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('name_kanji', sa.String(length=16), nullable=False),
    sa.Column('name_romaji', sa.String(length=64), nullable=False),
    sa.Column('avatar', sa.String(length=128), nullable=True),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('first_appearance_anime', sa.Integer(), nullable=True),
    sa.Column('first_appearance_manga', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_characters_name'), 'characters', ['name'], unique=True)
    op.create_index(op.f('ix_characters_name_kanji'), 'characters', ['name_kanji'], unique=False)
    op.create_index(op.f('ix_characters_name_romaji'), 'characters', ['name_romaji'], unique=False)
    op.create_table('fighting_styles',
    sa.Column('id', sa.String(length=32), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fighting_styles_name'), 'fighting_styles', ['name'], unique=True)
    op.create_table('voice_actors',
    sa.Column('id', sa.String(length=32), autoincrement=False, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_voice_actors_name'), 'voice_actors', ['name'], unique=True)
    op.create_table('allegiances',
    sa.Column('ally_left_id', sa.String(length=32), nullable=False),
    sa.Column('ally_right_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['ally_left_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['ally_right_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('ally_left_id', 'ally_right_id')
    )
    op.create_table('characters_categories',
    sa.Column('character_id', sa.String(length=32), nullable=False),
    sa.Column('category_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.UniqueConstraint('character_id', 'category_id', name='character_id_category_id')
    )
    op.create_table('characters_fighting_styles',
    sa.Column('character_id', sa.String(length=32), nullable=False),
    sa.Column('fighting_style_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['fighting_style_id'], ['fighting_styles.id'], ),
    sa.UniqueConstraint('character_id', 'fighting_style_id', name='character_id_fighting_style_id')
    )
    op.create_table('characters_voice_actors',
    sa.Column('character_id', sa.String(length=32), nullable=False),
    sa.Column('voice_actor_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['voice_actor_id'], ['voice_actors.id'], ),
    sa.UniqueConstraint('character_id', 'voice_actor_id', name='character_id_voice_actor_id')
    )
    op.create_table('family_members',
    sa.Column('relative_left_id', sa.String(length=32), nullable=False),
    sa.Column('relative_right_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['relative_left_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['relative_right_id'], ['characters.id'], ),
    sa.PrimaryKeyConstraint('relative_left_id', 'relative_right_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('family_members')
    op.drop_table('characters_voice_actors')
    op.drop_table('characters_fighting_styles')
    op.drop_table('characters_categories')
    op.drop_table('allegiances')
    op.drop_index(op.f('ix_voice_actors_name'), table_name='voice_actors')
    op.drop_table('voice_actors')
    op.drop_index(op.f('ix_fighting_styles_name'), table_name='fighting_styles')
    op.drop_table('fighting_styles')
    op.drop_index(op.f('ix_characters_name_romaji'), table_name='characters')
    op.drop_index(op.f('ix_characters_name_kanji'), table_name='characters')
    op.drop_index(op.f('ix_characters_name'), table_name='characters')
    op.drop_table('characters')
    op.drop_index(op.f('ix_categories_name'), table_name='categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
