"""Modify voice_actors and fighting_styles name

Revision ID: 3222d2ce3e5f
Revises: 4eca727a44ac
Create Date: 2018-08-11 10:56:49.768492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "3222d2ce3e5f"
down_revision = "4eca727a44ac"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(
        op.f("ix_fighting_styles_name"), "fighting_styles", ["name"], unique=True
    )
    op.create_index(op.f("ix_voice_actors_name"), "voice_actors", ["name"], unique=True)


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_voice_actors_name"), table_name="voice_actors")
    op.drop_index(op.f("ix_fighting_styles_name"), table_name="fighting_styles")


# ### end Alembic commands ###
