"""empty message

Revision ID: 41e2893ae3c3
Revises: 6dfda16ed428
Create Date: 2018-08-12 09:58:06.256589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "41e2893ae3c3"
down_revision = "6dfda16ed428"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "characters_categories",
        sa.Column("character_id", sa.String(length=32), nullable=False),
        sa.Column("category_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["category_id"], ["categories.id"]),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"]),
        sa.UniqueConstraint(
            "character_id", "category_id", name="character_id_category_id"
        ),
    )


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("characters_categories")


# ### end Alembic commands ###
