"""Add name to characters and renaming

Revision ID: 462eb13f48b8
Revises: 34784a7a1f52
Create Date: 2018-08-10 16:42:52.271831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "462eb13f48b8"
down_revision = "34784a7a1f52"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characters", sa.Column("first_appearance_anime", sa.Integer(), nullable=True)
    )
    op.add_column(
        "characters", sa.Column("first_appearance_manga", sa.Integer(), nullable=True)
    )
    op.add_column("characters", sa.Column("name", sa.String(length=16), nullable=False))
    op.create_index(op.f("ix_characters_name"), "characters", ["name"], unique=False)
    op.drop_column("characters", "first_anime_episode")
    op.drop_column("characters", "first_manga_chapter")


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characters",
        sa.Column(
            "first_manga_chapter", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.add_column(
        "characters",
        sa.Column(
            "first_anime_episode", sa.INTEGER(), autoincrement=False, nullable=True
        ),
    )
    op.drop_index(op.f("ix_characters_name"), table_name="characters")
    op.drop_column("characters", "name")
    op.drop_column("characters", "first_appearance_manga")
    op.drop_column("characters", "first_appearance_anime")


# ### end Alembic commands ###
