"""Modify character name

Revision ID: 4eca727a44ac
Revises: 4c243a0ea70a
Create Date: 2018-08-11 10:45:27.235329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4eca727a44ac"
down_revision = "4c243a0ea70a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_characters_name", table_name="characters")
    op.create_index(op.f("ix_characters_name"), "characters", ["name"], unique=True)


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_characters_name"), table_name="characters")
    op.create_index("ix_characters_name", "characters", ["name"], unique=False)


# ### end Alembic commands ###
