"""empty message

Revision ID: 596c44b4db2a
Revises: 43d723a00edc
Create Date: 2018-08-11 12:47:10.340161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "596c44b4db2a"
down_revision = "43d723a00edc"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "characters",
        "name",
        existing_type=sa.VARCHAR(length=32),
        type_=sa.String(length=16),
        existing_nullable=False,
    )
    op.drop_index("ix_characters_name", table_name="characters")
    op.create_index(op.f("ix_characters_name"), "characters", ["name"], unique=True)
    op.create_index(
        op.f("ix_fighting_styles_name"), "fighting_styles", ["name"], unique=True
    )
    op.create_index(op.f("ix_voice_actors_name"), "voice_actors", ["name"], unique=True)


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_voice_actors_name"), table_name="voice_actors")
    op.drop_index(op.f("ix_fighting_styles_name"), table_name="fighting_styles")
    op.drop_index(op.f("ix_characters_name"), table_name="characters")
    op.create_index("ix_characters_name", "characters", ["name"], unique=False)
    op.alter_column(
        "characters",
        "name",
        existing_type=sa.String(length=16),
        type_=sa.VARCHAR(length=32),
        existing_nullable=False,
    )


# ### end Alembic commands ###
