"""empty message

Revision ID: 6dfda16ed428
Revises: 3c0feabaedb5
Create Date: 2018-08-12 09:54:12.104727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6dfda16ed428"
down_revision = "3c0feabaedb5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.String(length=32), autoincrement=False, nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=128), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_name"), "categories", ["name"], unique=True)


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_categories_name"), table_name="categories")
    op.drop_table("categories")


# ### end Alembic commands ###
