"""Remove is_not_in_manga from characters

Revision ID: 799a2edfc0c6
Revises: 462eb13f48b8
Create Date: 2018-08-10 16:48:50.155758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "799a2edfc0c6"
down_revision = "462eb13f48b8"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters", "is_not_in_manga")


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characters",
        sa.Column("is_not_in_manga", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )


# ### end Alembic commands ###
