"""empty message

Revision ID: d162daa1f162
Revises: 41e2893ae3c3
Create Date: 2018-08-12 10:38:42.452212

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d162daa1f162"
down_revision = "41e2893ae3c3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "characters_fighting_styles",
        sa.Column("character_id", sa.String(length=32), nullable=False),
        sa.Column("fighting_style_id", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(["character_id"], ["characters.id"]),
        sa.ForeignKeyConstraint(["fighting_style_id"], ["fighting_styles.id"]),
        sa.UniqueConstraint(
            "character_id", "fighting_style_id", name="character_id_fighting_style_id"
        ),
    )


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("characters_fighting_styles")


# ### end Alembic commands ###
