"""Add fighting_styles

Revision ID: fafa75e5b468
Revises: f18ac1dc7490
Create Date: 2018-08-07 22:49:43.146402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "fafa75e5b468"
down_revision = "f18ac1dc7490"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "fighting_styles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("url", sa.String(length=32), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("fighting_styles")


# ### end Alembic commands ###
