"""Remove characters_voice_actors.id.

Revision ID: ff7b1174a2c4
Revises: 596c44b4db2a
Create Date: 2018-08-11 14:49:01.349073

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "ff7b1174a2c4"
down_revision = "596c44b4db2a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("characters_voice_actors", "id")


# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "characters_voice_actors", sa.Column("id", sa.INTEGER(), nullable=False)
    )


# ### end Alembic commands ###
